config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: 'devise/registrations#new'
  end

  resource 'medicine', path: '', controller: 'medicine', only: [] do
    get 'autocomplete'
    get 'cabinet'
    get 'information'
    get 'medicine_information'
    get 'about'
    post 'add_to_cabinet'
    post 'update_primary_medicine'
    delete 'destroy'
    get 'style_guide'
  end

  mount Flip::Engine => '/features'
end

app/views/shared/_authentication.html.erb
<% if user_signed_in? %>
  <%= link_to('sign out', destroy_user_session_path, :method => :delete, class: ("active" if current_page?(destroy_user_session_path)), id: mobile ? 'mobile-sign-out-link' : 'sign-out-link') %>
<% else %>
  <%= link_to('sign in', new_user_session_path, class: ("active" if current_page?(new_user_session_path)), id: mobile ? 'mobile-sign-in-link' : 'sign-in-link') %>
<% end %>

app/views/shared/_header.html.erb
  <div class='nav row'>
    <div class='col-span-5 logo'>
      <%= image_tag('logo.png') %><a href='/'><span class='bold'>PEN</span><span class='green-text bold'>CABINET</span></a>
    </div>

    <div class='col-span-7 t-right links'>
      <div class='visible-desktop'>
        <%= render :template => 'shared/_header_links', :locals => { mobile: false } -%>
      </div>

      <div class='mobile-menu hidden-desktop'>
        <button class='x lines-button' title='open all sections'><span class='lines'></span></button>
      </div>

      <div class='mobile-side-menu'>
        <%= render :template => 'shared/_header_links', :locals => { mobile: true }  -%>
      </div>

    </div>
  </div>

app/views/shared/_header_links.html.erb
<ul>
  <li><%= link_to('home', root_path, class: ("active" if current_page?(root_path))) %></li>
  <li class='visible-desktop'>|</li>
  <li><%= link_to('cabinet', cabinet_medicine_path, class: ("active" if current_page?(cabinet_medicine_path))) %></li>
  <li class='visible-desktop'>|</li>
  <li><%= link_to('about', about_medicine_path, class: ("active" if current_page?(about_medicine_path))) %></li>
  <li class='visible-desktop'>|</li>
  <li><iframe class='github-star' src="https://ghbtns.com/github-btn.html?user=excellaco&repo=open-cabinet&type=star&count=true" frameborder="0" scrolling="0" width="120px" height="30px"></iframe></li>
  <li class='visible-desktop'>|</li>
  <li><%= render :partial => 'shared/authentication', :locals => { mobile: mobile } %></li>
</ul>